name: 🧽 Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: 🧽 Lint
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 💽 Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: 🏗️ Setup Node
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔨 Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: 🧼 Lint
        run: |
          npm run lint
